apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-t-6.3.2
spec:
  replicas: 3
  selector:
    app: kibana-test
  template:
    metadata:
      labels:
        app: kibana-test
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.3.2
        ports:
        - containerPort: 5601

